### ISSUE TITLE
High-Level Training

### ISSUE THREAD

**Issue by Chu4nQ1n** [Ericonaldo/visual_wholebody#1]
Hi there, thank you for your impressive work. 

I encountered some problems when trying to train the high-level policy. Following the instructions, I added a pre-trained low-level policy path in the config file. After training for 23 timesteps, the ipdb debugger was invoked. Upon commenting out the ipdb, it seems to be a CUDA memory access issue. Have you ever encountered this before, and how did you solve it? 

```
Traceback (most recent call last):
  File "train_multistate.py", line 227, in <module>
    trainer.train()
  File "/home/ubuntu/Downloads/visual_wholebody_fork/third_party/skrl/skrl/trainers/torch/sequential.py", line 77, in train
    self.single_agent_train()
  File "/home/ubuntu/Downloads/visual_wholebody_fork/third_party/skrl/skrl/trainers/torch/base.py", line 177, in single_agent_train
    next_states, rewards, terminated, truncated, infos = self.env.step(actions)
  File "/home/ubuntu/Downloads/visual_wholebody_fork/high-level/utils/wrapper.py", line 136, in step
    self._obs_dict, reward, terminated, info = self._env.step(actions)
  File "/home/ubuntu/Downloads/visual_wholebody_fork/high-level/envs/b1z1_pickmulti.py", line 383, in step
    res = super().step(actions)
  File "/home/ubuntu/Downloads/visual_wholebody_fork/high-level/envs/b1z1_base.py", line 1307, in step
    self._refresh_sim_tensors()
  File "/home/ubuntu/Downloads/visual_wholebody_fork/high-level/envs/b1z1_pickmulti.py", line 292, in _refresh_sim_tensors
    super()._refresh_sim_tensors()
  File "/home/ubuntu/Downloads/visual_wholebody_fork/high-level/envs/b1z1_base.py", line 797, in _refresh_sim_tensors
    self._last_dof_vel = self._dof_vel.clone()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
``` 

System Info: 
Commit : 7b2b903
OS: Ubuntu 20.04
GPU: RTX 4070 Ti
CUDA: 12.2, GPU Driver: 535.171.04 

The low-level policy training goes well under this configuration.

**Comment by Ericonaldo** [comment]
Usually, this is due to out of mem, trying less number of parallel environments.

**Comment by Chu4nQ1n** [comment]
> Usually, this is due to out of mem, trying less number of parallel environments.

Thanks, solved by changing numEnvs 10240 --> 4096.
